name: veggies_notes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-179.0.dev <4.0.0'

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.7.1
  equatable: ^2.0.5
  firebase_core: ^2.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  google_generative_ai: ^0.2.0
  google_maps_flutter: ^2.2.4
  line_icons: ^2.0.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
