// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiqutPrdUAAMZfKjkoeP9ruhQRggAvDhQ',
    appId: '1:916415988125:web:53f1cad56671edffe5af74',
    messagingSenderId: '916415988125',
    projectId: 'veggiesnotes',
    authDomain: 'veggiesnotes.firebaseapp.com',
    storageBucket: 'veggiesnotes.appspot.com',
    measurementId: 'G-HZ9CV22KRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgbLXkFPYP3-igzuShVBZHsbcC2mGzRO0',
    appId: '1:916415988125:android:73751a7a5f6bc2f1e5af74',
    messagingSenderId: '916415988125',
    projectId: 'veggiesnotes',
    storageBucket: 'veggiesnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVns1RokEWOn4gIE3rVGb9jUw-QLVHByY',
    appId: '1:916415988125:ios:7f1bcbd8629aa8ace5af74',
    messagingSenderId: '916415988125',
    projectId: 'veggiesnotes',
    storageBucket: 'veggiesnotes.appspot.com',
    iosClientId: '916415988125-riug0k373famhnc9dbqpgp734ep9qlq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.veggiesNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVns1RokEWOn4gIE3rVGb9jUw-QLVHByY',
    appId: '1:916415988125:ios:a1f2acaf61a00572e5af74',
    messagingSenderId: '916415988125',
    projectId: 'veggiesnotes',
    storageBucket: 'veggiesnotes.appspot.com',
    iosClientId: '916415988125-4kl67ni950ns8f02abf9ar9do5n4bb1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.veggiesNotes.RunnerTests',
  );
}
